### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by ghost** [mfelsche/ponyfmt#1]
Is ponyfmt still actively maintained?

**Comment by mfelsche** [comment]
Good question.

The sad but true answer is, it is not. But i am happy to help anyone who wants to make this a thing as much as i possibly can. Feel free to reach out to me.

**Comment by ghost** [comment]
I was just interested in this since I'm learning Pony and I'm used to Go.. I'm just using Pony in a hobby project. Since I'm still learning Pony this goes way above my head, thank you for the quick response.
